using System.Collections.Generic;

namespace StandardIo.ArchitectureDiagram.Core.Models.ArchitectureV6;

public enum PlanningDiagnosticSubject
{
    SemanticNode,
    SemanticLink,
    PhysicalNode,
    PhysicalLink,
    Grid,
    Cell,
    Row,
    Column,
    RouteStep,
    StraightRun,
    Lane,
    TrackConstraint,
    PhysicalSegment
}

public enum ArchitecturePlanningDiagnosticSeverity
{
    Info,
    Warning,
    Error
}

public sealed record ArchitecturePlanningDiagnostic(
    string Code,
    string Message,
    PlanningDiagnosticSubject Subject,
    string? SubjectId,
    ArchitecturePlanningDiagnosticSeverity Severity = ArchitecturePlanningDiagnosticSeverity.Error);

public sealed record ArchitectureNodeGridEvidence(
    string PhysicalNodeId,
    string SemanticNodeId,
    string RowId,
    string AnchorColumnId,
    IReadOnlyList<string> FootprintColumnIds,
    string? PositionalOwnerId,
    IReadOnlyList<string> PositionalChildIds,
    string SubtreeId);

public sealed record ArchitectureV6TrackCapacityEvidence(
    string GridId,
    RouteAxis Axis,
    string TrackId,
    int LaneCount,
    string? FirstLane,
    string? LastLane,
    int RequiredExtent,
    int ActualExtent,
    int Deficit,
    int Surplus,
    IReadOnlyList<string> RouteIds);

public sealed record ArchitectureV6PhysicalRouteFindingEvidence(
    string RouteId,
    string FindingType,
    string ComponentId,
    int SegmentIndex,
    IReadOnlyList<string> Cells,
    string ActualStart,
    string ActualEnd);

public sealed record ArchitectureV6PhysicalRouteEvidence(
    string RouteId,
    bool IsValid,
    IReadOnlyList<string> Findings,
    IReadOnlyList<string> ComponentIds,
    IReadOnlyList<string> ComponentTypes,
    IReadOnlyList<string> OrderedCells,
    IReadOnlyList<string> LaneIds,
    IReadOnlyList<string> TrackIds,
    IReadOnlyList<string> RawPoints,
    IReadOnlyList<string> ReducedPoints,
    string? SourceTerminal,
    string? DestinationTerminal,
    IReadOnlyList<ArchitectureV6PhysicalRouteFindingEvidence> FindingEvidence);

public sealed record ArchitecturePlanningMetrics(
    int SemanticNodeCount,
    int SemanticLinkCount,
    int PhysicalNodeCount,
    int PhysicalLinkCount,
    int ProjectGridCount,
    int GridRowCount,
    int GridColumnCount,
    int OccupiedCellCount,
    int RouteUsedCellCount,
    IReadOnlyDictionary<string, int> TopologyFamilyCounts,
    int RouteStepCount,
    int StraightRunCount,
    int LaneCount,
    RelativeRectangle? DiagramBounds,
    int ValidationFindingCount,
    IReadOnlyDictionary<string, int>? DuplicateCountsBySemanticNode = null,
    int RootCount = 0,
    int ExternalNodeCount = 0,
    int StandaloneNodeCount = 0,
    int CycleCount = 0,
    int LogicalLayerCount = 0,
    int AnchorCellCount = 0,
    int FootprintCellCount = 0,
    int SubtreeReservationCount = 0,
    int PositionalOwnerCount = 0,
    int UnplacedNodeCount = 0,
    int OverlappingFootprintCount = 0,
    int IncompatibleReservationCount = 0,
    int SizedNodeCount = 0,
    int GeometryProjectCount = 0,
    int GeometryGridCount = 0,
    int GeometryWidth = 0,
    int GeometryHeight = 0,
    int GeometryCollisionCount = 0,
    int GeometryContainmentViolationCount = 0,
    int InvalidDimensionCount = 0,
    int FootprintExpansionRequirementCount = 0,
    int PlacementRebuildCount = 0,
    int ExpandedNodeCount = 0,
    int UnsupportedRouteCount = 0,
    IReadOnlyDictionary<string, int>? LaneAllocationConflictCounts = null,
    IReadOnlyDictionary<string, string>? ExpandedNodeSpans = null,
    int InvalidatedRouteCount = 0,
    int RebuiltReservationCount = 0,
    int ShiftedRegionCount = 0,
    IReadOnlyDictionary<string, int>? SizingConstraintCounts = null,
    IReadOnlyDictionary<string, int>? SizingContributionExtents = null,
    int SizingSolverIterations = 0,
    bool SizingIdempotent = false,
    int LargestRowExtent = 0,
    int LargestColumnExtent = 0,
    int LargestSpanMinimum = 0,
    int UnsatisfiedSizingConstraintCount = 0,
    int StructuralRowCountBeforeRouting = 0,
    int StructuralColumnCountBeforeRouting = 0,
    int StructuralRowCountAfterRouting = 0,
    int StructuralColumnCountAfterRouting = 0,
    IReadOnlyDictionary<string, int>? StructuralRowRoleCounts = null,
    IReadOnlyDictionary<string, int>? StructuralColumnRoleCounts = null,
    int RouteOnlyRowCount = 0,
    int RouteOnlyColumnCount = 0,
    IReadOnlyDictionary<string, long>? StageTimingMilliseconds = null,
    IReadOnlyDictionary<string, int>? StageInvocationCounts = null,
    int CellsBeforeRouting = 0,
    int CellsAfterRouting = 0,
    int HorizontalLaneCount = 0,
    int VerticalLaneCount = 0,
    int MaximumHorizontalLanesInDomain = 0,
    int MaximumVerticalLanesInDomain = 0,
    IReadOnlyList<ArchitectureNodeGridEvidence>? NodeGridEvidence = null,
    long ProfileComputationMilliseconds = 0,
    long ProfileCompositionMilliseconds = 0,
    long ColumnMaterializationMilliseconds = 0,
    long ReservationConstructionMilliseconds = 0,
    int SubtreeProfileCacheHits = 0,
    int SubtreeProfileCacheMisses = 0,
    long IntervalCompatibilityChecks = 0,
    long LaneAllocationMilliseconds = 0,
    int LaneDomainCount = 0,
    int LaneOrderingVertexCount = 0,
    int LaneOrderingEdgeCount = 0,
    int LaneOrderingCycleCount = 0,
    int TurnCellCount = 0,
    int MaximumTurnsInCell = 0,
    long LaneIntervalComparisons = 0,
    int LaneCapacityRequirementCount = 0,
    long SizingConstraintConstructionMilliseconds = 0,
    long SizingSolverMilliseconds = 0,
    long SizingOffsetCompilationMilliseconds = 0,
    long SizingNodeEnvelopeMilliseconds = 0,
    long SizingReservationEnvelopeMilliseconds = 0,
    long SizingValidationMilliseconds = 0,
    long SizingEvidenceSerializationMilliseconds = 0,
    int AbsoluteNodeCount = 0,
    int AbsoluteTerminalCount = 0,
    int PhysicalRouteCount = 0,
    int PhysicalSegmentCount = 0,
    int PhysicalBendCount = 0,
    int PhysicalCleanCrossingCount = 0,
    int PhysicalTransitionCount = 0,
    int TotalRouteLength = 0,
    int MaximumRouteLength = 0,
    int PhysicalNodeOverlapCount = 0,
    int RouteNodeIntersectionCount = 0,
    int SharedCollinearSegmentCount = 0,
    int SharedBendCount = 0,
    int InvalidCrossingCount = 0,
    int TerminalFindingCount = 0,
    int OwnershipTransformFindingCount = 0,
    int LabelGeometryUnavailableCount = 0,
    IReadOnlyDictionary<string, int>? PhysicalTopologyCounts = null,
     IReadOnlyDictionary<string, long>? PhysicalStageTimingMilliseconds = null,
     int BoundaryValidRouteCount = 0,
     int BoundaryInvalidRouteCount = 0,
     int BoundaryFindingCount = 0,
     IReadOnlyDictionary<string, int>? BoundaryComponentTypeCounts = null,
     IReadOnlyDictionary<string, int>? BoundaryAdjacencyPairCounts = null,
     IReadOnlyDictionary<string, int>? BoundaryMatchingPairCounts = null,
     IReadOnlyDictionary<string, int>? BoundaryMismatchedPairCounts = null,
     int BoundaryMatchingPairCount = 0,
     int BoundaryMismatchedPairCount = 0,
     int CompleteTurnContractCount = 0,
     int IncompleteTurnContractCount = 0,
     int InvalidPhysicalRouteCount = 0,
     int AttemptedPhysicalSegmentCount = 0,
     int DiagonalPhysicalSegmentCount = 0,
     int CorridorEscapeCount = 0,
     int ComponentContinuityFailureCount = 0,
     int SourceStubDirectionFailureCount = 0,
     int DestinationStubDirectionFailureCount = 0,
     IReadOnlyList<ArchitectureV6TrackCapacityEvidence>? TrackCapacity = null,
     IReadOnlyList<ArchitectureV6PhysicalRouteEvidence>? RouteEvidence = null);

public sealed record ArchitecturePlanningDiagnostics(
    IReadOnlyList<ArchitecturePlanningDiagnostic> Findings,
    ArchitecturePlanningMetrics Metrics);

public sealed record PlannedArchitectureValidationResult(
    bool IsValid,
    IReadOnlyList<ArchitecturePlanningDiagnostic> Findings);
